### PR TITLE
Add Support for driver's full finger encoding

### PR DESCRIPTION
**Pull request by JohnRThomas**
This change adds the new encoding format that the driver supports.

### CODE REVIEW

**Review by danwillm — CHANGES_REQUESTED** [review]
Thanks for these changes!
I think there's a debate to be made over whether we support splay and joints as a wholly separate encoding option, or as a config option for enabling splay or joint.

@lucas-vrtech might have some more thoughts on this

**Comment by JohnRThomas** [comment]
What does the splay default to when it is not specified? Is there much difference between the FW sending a default value and driver coming up with a default value?

**Comment by LittleNyanCat** [comment]
> I think there's a debate to be made over whether we support splay and joints as a wholly separate encoding option, or as a config option for enabling splay or joint.

When working on my gyro thing I've thought of reworking the way encoding is done a bit so that keys can be arbitrarily added and omitted using #ifdefs

**Comment by danwillm** [comment]
> What does the splay default to when it is not specified? Is there much difference between the FW sending a default value and driver coming up with a default value?

If there is no splay provided by the firmware, the driver will just skip calculating splay and will remain as normal. Same for the joints.

**Pull request closed without merging**
