### PR TITLE
Added Reverb G2 controller mount and a README for controller mount intrusions 

### PR DESCRIPTION
**Pull request by 0611zman**
I added and deleted something just to test something.

I am interested to hear your option on the readme for controller mounting. I was thinking for each mount we could have some basic instructions to make sure they are used properly. The reason I thought this was important is that tracking quality for these gloves really makes a difference

I have also attached 2 photos of the mount in use!

image0
IMG_0473
.

### CODE REVIEW

**Review by lucas-vrtech — CHANGES_REQUESTED** [review]
Let's go ahead and move this readme documentation into the wiki, I think that would be a better spot for it. Currently printing out the controller mount to take a look, but once you remove the readme I'll merge this in :)

**Comment by lucas-vrtech** [comment]
Also, I wonder if there's a way we can streamline this to not need support structures to print?

**Comment by 0611zman** [comment]
Great! I was able to streamline the model and it is very smooth. I was able to print mine without supports but I know not every printer will print the same. Once I print a few of them to confirm they are good, I'll send the model over!

**Comment by lucas-vrtech** [comment]
Awesome sounds good! 
By the way, for now, if you have your current design on thingiverse or something and want to add it to the [community accessory list](https://github.com/LucidVR/lucidgloves/wiki/Community-Design-List), feel free to do so!

**Comment by 0611zman** [comment]
Would you like to put the model in the community page and the official hardware folder? Or just one or the other?

**Comment by 0611zman** [comment]
I was able to print a few of the models without supports but I may have just gotten lucky. I have an ender 3 pro, lmk how yours turn out when you get the time. Thanks!

**Comment by lucas-vrtech** [comment]
Alright cool so go ahead and make a separate page for this model (thingiverse, github repo, etc) with your instructions there, and then link it in the community design list. Thanks

**Pull request closed without merging**
