### PR TITLE
Suport for WiFI

### PR DESCRIPTION
**Pull request by ElectricTurtle32**
Support for WiFi in the arduino code.

### CODE REVIEW

**Comment by ElectricTurtle32** [comment]
DRAFT CUZ IDK HOW TO TURN IT INTO A DRAFT (caps intended)

**Comment by lucas-vrtech** [comment]
Closing this for now, but feel free to reopen if/when you're still working on wifi :)

**Comment by ElectricTurtle32** [comment]
Ok

**Comment by minystreem** [comment]
#72

**Pull request closed without merging**
