### PR TITLE
Added ESP32 Package Installation Documentation

### LINKED ISSUE #16: Add documentation for adding required ESP32 libraries
This is a pretty quick first issue if someone wants to take it,
Currently in order to use the firmware with ESP32, one needs to get the ESP32 libraries from the Arduino IDE package manager,
And in order to use the servos for force feedback, one needs to get the ESP32servo library

### PR DESCRIPTION
**Pull request by Zach710032**

### CODE REVIEW

**Comment by Zach710032** [comment]
Issue #16

**Comment by lucas-vrtech** [comment]
Hello, this looks great! ~~However, instead of adding it to the README.md, could you please add this as a page to the wiki? Thanks!~~ EDIT: I misread the diff. Looks great.

**Review by lucas-vrtech — APPROVED** [review]
Approved

**Comment by Zach710032** [comment]
Yup, I'll do it as soon as I can. Excited for that prototype 4 build guide!

**Pull request merged**
