### PR TITLE
Servo scaling

### PR DESCRIPTION
**Pull request by kskoczyk**
This PR adds individual servo scaling for each finger based on pot readings
And a fix to servos retracting when you go out of bounds (code proposed by danwillm#8254 on Discord, forum thread: https://discord.com/channels/784543299045818420/1017766753012559973)

### CODE REVIEW

**Comment by JohnRThomas** [comment]
I had something similar: https://github.com/LucidVR/lucidgloves/pull/56
I didn't realize the PR got closed when I deleted the branch off my repository, whoops.

I ending up basing mine off the calibration data instead of hard coded values as recommended by @danwillm.

I would also recommend squashing your change into a single commit.

**Comment by danwillm** [comment]
Would you mind creating two separate PRs - one for the fix to the servos and the other scaling? Cheers!

**Comment by kskoczyk** [comment]
Hi, sorry for the delay, I'm busy now, so I will get on it this weekend. I agree with both suggestions.
@JohnRThomas That is interesting, I will definitely look at how you implemented it.
@danwillm Yeah, if you're okay with me creating a PR, then sure.

**Comment by kskoczyk** [comment]
Closing this PR to add two separate ones.
https://github.com/LucidVR/lucidgloves/pull/87
https://github.com/LucidVR/lucidgloves/pull/88

**Pull request closed without merging**
