### PR TITLE
Change to GreenPotElasticHolder.stl

### PR DESCRIPTION
**Pull request by 0611zman**
Added a green potentiometer elastic holder.

### CODE REVIEW

**Review by 0611zman — COMMENTED** [review]
This is the right one, the without "again" is the wack file. Sorry for the inconvenience!

**Comment by lucas-vrtech** [comment]
Awesome, thanks for the PR. I'll print it out this week to test

**Review by lucas-vrtech — CHANGES_REQUESTED** [review]
Part has an accidental overhang that will make printing difficult on some printers. Feel free to fix, or I'll go ahead and upload my own version once I have my solidworks files.

image

**Comment by 0611zman** [comment]
Let me fix that real quick! Thank you!

**Review by lucas-vrtech — CHANGES_REQUESTED** [review]
The slit is still there. Looks like more needs to be shaved off.

**Comment by 0611zman** [comment]
Oh sorry man, I thought you were talking about something else! That should fix it there!

**Review by lucas-vrtech — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
